version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: procrastination
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  web:
    image: procrastination-server
    depends_on:
      - db
    ports:
      - '80:80'
